set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

if(PORT STREQUAL "sdl2")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()
if(PORT STREQUAL "sdl2-image")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()
if(PORT STREQUAL "libjpeg-turbo")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()
if(PORT STREQUAL "libpng")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()
if(PORT STREQUAL "zlib")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()