name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

jobs:  
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-2019']
        include:
          - os: 'windows-2019'
            triplet: 'x64-windows'
            configuration: x64-Release
    env:
      buildDir: '${{ github.workspace }}/build'
    steps:
    - uses: actions/checkout@v2

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install vcpkg
      uses: lukka/run-vcpkg@v6
      with:
        setupOnly: true
        appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
        vcpkgTriplet: ${{ matrix.triplet }}
        additionalCachedPaths: ${{ env.buildDir }}/vcpkg_installed
    
    - name: 'Run CMake with Ninja, install dependencies with vcpkg, build with CMake'
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeSettingsJson
        useVcpkgToolchainFile: true
        buildDirectory: ${{ env.buildDir }}
        configurationRegexFilter: '${{ matrix.configuration }}'
      
